/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package word_guessing_game;

import java.util.ArrayList;
import java.util.Scanner;

public class Game {

    public Integer attempts;
    ArrayList<Character> guessLetterArray = new ArrayList<Character>();
    StringBuilder builder;
    String word;
    Character character;

    public Game(WordChoser choser) {
        this.word = choser.getRandomWordFromDictionary();
        attempts = 10;
        builder = new StringBuilder(word);
    }

    public String getWordToGuess() {
        for (int i = 1; i < builder.length(); i++) {
            if (!guessLetterArray.contains(word.charAt(i))) {
                builder.replace(i, i + 1, "_");
            } else if (guessLetterArray.size() > 0) {
                if (character == word.charAt(i)) {
                    builder.replace(i, i + 1, character.toString());
                }
            }
        }
        return builder.toString();
    }

    public Boolean isGameLost() {
        if (attempts == 0){
            return true;
        }
        return false;
    }

    public Boolean isGameWon() {
        if (getWordToGuess().contains("_")==false) {
            return true;
        }
        return false;
    }

    public String guessLetter(char character) {
        this.character = Character.toUpperCase(character);
        character = Character.toUpperCase(character);

        if (guessLetterArray.contains(character)) {
            return ("You have already tried that letter.");
        }

        guessLetterArray.add(character);
        if (word.contains(String.valueOf(character))) {
            return ("Good guess!");
        }
        attempts--;
        return String.format("Nope, not really. %d attempts remaining", attempts);
    }

    public Integer getRemainingAttempts() {
        return attempts;
    }

    public static void main(String[] args) {
        //maybe put this in a play() function?
        WordChoser wordchoser = new WordChoser();
        Game game = new Game(wordchoser);
        Scanner reader = new Scanner(System.in);
        System.out.println("Welcome to the word guessing game!");
        System.out.println("This is your word:");

        while (game.isGameWon()==false) {
            System.out.printf("\nYour current state is: %s\n", game.getWordToGuess());
            System.out.println("Give me a letter:");
            char guess = reader.next().charAt(0);
            System.out.println(game.guessLetter(guess));

            if (game.isGameLost()) {
                System.out.println("BOO! This is an easy game! You fooking doughnut!");
                break;
            }
            if (game.isGameWon()) {
                System.out.println("CONGRATULATIONS!!!!! *fireworks exploding and shit*");
                break;
            }
        }
        reader.close();
}}
